### ISSUE TITLE
認証をサイト毎にかけたい

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#135]
工事中のときとか

**Comment by mtsmfm** [comment]
アカウント認証にしよう

**Comment by okkez** [comment]
adminやeditorとしてログインしているときに、サイトのフッターにでもそれ用のメニューがあると便利そう。

**Comment by okkez** [comment]
- アカウント認証
- robots.txt で noindex (/users/sign_in)

**Comment by mtsmfm** [comment]
/users/sign_in は普通に見れる

**Comment by tricknotes** [comment]
`Site#opened` で判定する

**Comment by mtsmfm** [comment]
Site#opened で判定
