### ISSUE TITLE
利用規約やプライバシーポリシーをどうする？

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#14]
サービス固有になると思われるので、その設定(切り替え?)方法をどうしよう…

**Comment by okkez** [comment]
DBに入れるか、assetsと同じリポジトリに入れておくか。

**Comment by okkez** [comment]
または、記事の一種と見做して記事として書いてもらってカテゴリかタグで利用規約とかプライバシーポリシーとか設定するといい感じに表示できるとか？

**Comment by mtsmfm** [comment]
![image](https://cloud.githubusercontent.com/assets/1796864/11704449/3eae49d6-9f2b-11e5-9fd9-1e6f07ac4555.png)
