### ISSUE TITLE
ヘッダにロゴ画像を設定できるようにする

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#146]
アップロードできればよさそう

**Comment by okkez** [comment]
ImageUploaderは同じのを使いたいので #158 がマージされたら着手する

**Comment by okkez** [comment]
ロゴはアップロード**だけ**できればいいのかどうか気になる。
サイトが持つ画像は以下の通り。
- logo_url
- favicon_url
- mobile_favicon_url

どっちでも設定できるようにするか、アップロードだけできるようにするか。

**Comment by okkez** [comment]
どっちでも設定できるようにしておいて、アップロードされたのがあったらそちらを優先するようにしようか。

**Comment by okkez** [comment]
うーむ、fixed page の integration test で SiteDecorator のメソッドが見えなくて怒られるぞ。
