### ISSUE TITLE
フッタにリンクを設定できるようにする

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#148]
- 固定ページへのリンク
- 外部サイトへのリンク

の 2 種類がありそう。
URL を設定できて、並びかえができるだけでいいかも。

**Comment by myokoym** [comment]
- 固定ページを一覧表示するのではなく、URLを設定できるようにする
  - フッタに表示しない固定ページがあるかも
  - 外部サイトのための固定ページは作りたくない
