### ISSUE TITLE
カラーテーマを管理画面から変更できる

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#150]
sass の variable を弄れるといいかもしれない。

**Comment by tricknotes** [comment]
「サービスの立ち上げを早くする」というのがこの issue のゴールです。
そのために、次のあたりを目指してみます。
- asset を置き場(S3 的なもの)なしでサービスが立ち上げられる
- 設定なしでそこそこの見栄えができあがる

ひとまずは、[`app/assets/stylesheets/themes/default/_variables.sass`](https://github.com/bm-sms/daimon-news-multi-tenant/blob/master/app/assets/stylesheets/themes/default/_variables.sass) 相当のものを管理画面からサイトごとに設定できるとよいのかな…。

**Comment by mtsmfm** [comment]
まだ要らない!
