### ISSUE TITLE
モデルにvalidationを追加する

### ISSUE THREAD

**Issue by okkez** [bm-sms/daimon-news-multi-tenant#168]
最低限 null 制約のあるカラムについてはモデル側にvalidationを追加する。

**Comment by okkez** [comment]
最低限 null 制約のあるカラムについてはモデル側にvalidationを追加する。

**Comment by myokoym** [comment]
合わせて該当するモデルのテストも追加する。

**Comment by mtsmfm** [comment]
closed via #183, #186
