### ISSUE TITLE
draper に置き換える？

### ISSUE THREAD

**Issue by okkez** [bm-sms/daimon-news-multi-tenant#169]
今 ActiveDecorator を使っているけど draper に置き換える？
勝手にラップされてしまうのがちょっと辛い感がある。

**Comment by tricknotes** [comment]
draper は decorator パターンによる実装なので、デコレート前後で別のオブジェクトになってハマることがあって辛かった記憶があります…。
ということで、個人的には ActiveDecorator に :+1: です。

他のかたはどうでしょうかねー？

**Comment by mtsmfm** [comment]
僕も個人的には ActiveDecorator に :+1: かなぁと思っています

`decorate` が自動かどうかは好き好きなので僕はどっちでもいいと思うんですが

> デコレート前後で別のオブジェクトに

がいろいろ影響があって、たとえば kaminari 用にちょっと考慮しないといけなかったり

https://github.com/drapergem/draper#using-pagination

するのがつらいなぁという感想でした。

**Comment by okkez** [comment]
では、ActiveDecoratorでいきましょう！！ :bow:

**Comment by tricknotes** [comment]
りょうかいです！
辛い感じについて会話できてよかったです！
