### ISSUE TITLE
AcitveAdminの見た目を整える

### ISSUE THREAD

**Issue by okkez** [bm-sms/daimon-news-multi-tenant#171]
- Siteの項目が多すぎてindex見辛い
- Siteのshowで順番を整えたい
- Siteのformでアップロード済みの画像を表示したい
- Postのformで順番を整えたい
- Postのshowでmarkdownの変換後を表示したい

**Comment by tricknotes** [comment]
:+1: 
もしかして、そろそろ ActiveAdmin やめたい気持ちが高まっていたりしますか？

**Comment by okkez** [comment]
これらは簡単に解決できるはずなので、まだいけます！！

**Comment by mtsmfm** [comment]
no longer used
