### ISSUE TITLE
`Post#original_id` に依存せず記事を表示できるようにする

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#172]
`Post#original_id` が必須ではなくなって記事が登録できるようになりましたが、そうすると今度は公開用の画面から記事を表示する方法がなくなってしまいました。(URL に origina_id が含まれることを期待しているため)

related to https://github.com/bm-sms/daimon-news-multi-tenant/issues/166

**Comment by okkez** [comment]
#177 と合わせてやろうと思います。

**Comment by okkez** [comment]
original_id 削除しよう。

**Comment by okkez** [comment]
もしかして GET `/posts/?original_id=xxx`  されたら、いい感じにリダイレクトして `/posts/:id` に飛ぶと便利？
