### ISSUE TITLE
検索

### ISSUE THREAD

**Issue by myokoym** [bm-sms/daimon-news-multi-tenant#185]
- 記事を検索したいニーズがありそう
- 実装案
  - LIKE検索で済ませる（遅いけどお手軽）
  - 全文検索エンジンを使う（速いけど運用が複雑になる）

**Comment by mtsmfm** [comment]
- 記事のタイトル、本文、著者情報 (?) から検索

**Comment by mtsmfm** [comment]
一致した位置は出なくてもいいような気はするけど出たら嬉しい

**Comment by mtsmfm** [comment]
検索した結果、記事のタイトル一覧が並んでいればそれで ok

**Comment by mtsmfm** [comment]
固定ページは対象外

**Comment by tricknotes** [comment]
本文は、 Markdown を HTML としてレンダーした結果のテキスト部分から検索する

**Comment by okkez** [comment]
HTMLへの変換結果はDBに入れても良いのでは、と思いました。
変換部分のロジックをちょいちょい変えるなら、今のままでいいけど、一旦決まったらほとんど変えない気がするので、変換結果をカラムに入れておいた方が便利なのでは？と思いました。

**Comment by myokoym** [comment]
#288 のpull requestで基本機能について対応しました。
主な対応内容は以下です。
- [x] 記事のタイトル、本文、関係者から検索
- [x] 記事のタイトルを表示
- [x] 関係者で絞り込み
- [x] 公開後に公開停止した記事が検索で引っかかってしまわないようにする https://github.com/bm-sms/daimon-news-multi-tenant/pull/288/files#r54970392

別PRで進める:
- [ ] テキスト抽出（マークダウンの記号で引っかからないようにする）
- [x] https://github.com/bm-sms/daimon-news-multi-tenant/pull/288#discussion_r54832043
- [ ] 著者情報検索のレビュー対応（著者情報フルネームの順位を改善）
  - [ ] https://github.com/bm-sms/daimon-news-multi-tenant/commit/c15ca8bc8211a61f25b223838cb623390e6ebba2#commitcomment-16527154
- [ ] 著者情報検索のレビュー対応（著者情報の重み付け改善）
  - [ ] https://github.com/bm-sms/daimon-news-multi-tenant/commit/c15ca8bc8211a61f25b223838cb623390e6ebba2#commitcomment-16557270
- [x] strong parameterでpermitするの減らす？ https://github.com/bm-sms/daimon-news-multi-tenant/pull/288#discussion_r55311282
- [x] 検索結果のページネーションは不要？ https://github.com/bm-sms/daimon-news-multi-tenant/pull/288#issuecomment-193617934
- [ ] 検索結果ページでは検索ボックスはサイドバーではなく検索結果のところに表示？ https://github.com/bm-sms/daimon-news-multi-tenant/pull/288#issuecomment-193616616
- [x] 検索後に検索ボックスが空になってしまう
- [x] サムネイルを表示する
- [ ] 検索結果をスコア順に並べる（今はARのモデルにマッピングするときに順序が失われるので、ひとまず最新日付順にしている）

**Comment by okkez** [comment]
issue を見落しそうなので、残タスクは別issueに切り出した。
