### ISSUE TITLE
.html 以外の 404 がエラーになる

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#203]

**Comment by myokoym** [comment]
500 エラーになるのはTemplate is missingになるケース:
- http://localhost:3000/category/category1.xml
- http://localhost:3000/category/2.json
- など

`respond_to`を使ってHTML以外は404に飛ばせばいいのかな。

**Comment by myokoym** [comment]
`respond_to`は各アクションに書く必要があってつらそう。
Rambulanceで設定できないか調べてみる。

**Comment by myokoym** [comment]
`config/initializers/rambulance.rb`の↓の設定だけだと、内部的には404になるけど
`/errors/not_found.html.erb`は表示されず、500 Internal Server Errorと表示される。
（ローカル環境で`config.consider_all_requests_local = false`にして確認）

``` ruby
  config.rescue_responses = {
    "ActionView::MissingTemplate" => :not_found
  }
```

**Comment by myokoym** [comment]
`ActionView::MissingTemplate`自体は500エラーにしておきたいので、
`.html`以外（`.json`や`.xml`など）は`.html`にフォールバックする方針がよさそう。

**Comment by myokoym** [comment]
`before_filter`で`request.format = :html`とすればできそう。

↑を常にやるとHTML以外のテンプレートがある場合でも常にHTMLを使うようになってしまうので、
フィード（XML）などが表示されなくなってしまう。

エラーのときだけフォールバックするようにしたいけど、どう判断すればよいのか悩ましい。
コントローラーごとに設定するのが無難かな…。
