### ISSUE TITLE
og:descriptionに改行が入ることがある

### ISSUE THREAD

**Issue by myokoym** [bm-sms/daimon-news-multi-tenant#220]
カテゴリーのページで確認。
本文に改行が入っていても、og:descriptionに入れるときに削除したほうがよさそう。

**Comment by myokoym** [comment]
meta-tags gemの設定とかでできないかと思ったけど、できなそうなので素直にgsubするか…

**Comment by okkez** [comment]
`MetaTags::TextNormalizer` が全部特異メソッドで定義しているから、`ApplictionHelper` に `include` する方法だと使えないのが残念。
