### ISSUE TITLE
オートリンクが無効

### ISSUE THREAD

**Issue by okkez** [bm-sms/daimon-news-multi-tenant#221]
Related to #214

**Comment by okkez** [comment]
kramdown の autolink は `<http...>` みたいに `<>` で囲まないとダメだ。

**Comment by okkez** [comment]
kramdown の GFM でも autolink は `<>` で囲まないとダメだー
本体に手を入れないといけない。

**Comment by tricknotes** [comment]
なるべくポータブルな Markdown を維持しておきたいので、Parser 独自の拡張記法は入れずに済むと嬉しい感じがしますね…。

**Comment by okkez** [comment]
github.com の GFM だと http://github.com でリンクになるので kramdown のバグっすねー

**Comment by okkez** [comment]
雑にやってみたけど、全然ダメだった。戻ったらちゃんとやろう。

**Comment by okkez** [comment]
できたのでDOM比較ツールができ次第マージしてもらおう

**Comment by tricknotes** [comment]
:raising_hand:
Wait a moment. I'm now working for it :sunglasses:

**Comment by okkez** [comment]
テストしてみたら、ちょっとまずいケースがあった。。。 :bow:

**Comment by okkez** [comment]
```
http://www.example.com
http://www.example.com
http://www.example.com
```

みたいに書くと、おかしくなるなぁ。

**Comment by okkez** [comment]
間に空行入れると、大丈夫だけど。

```
http://www.example.com/foo text
```

が

```
<a href="http://www.example.com/foo text">http://www.example.com/foo text</a>
```

みたいになって嬉しくない。

**Comment by okkez** [comment]
以下のケースには対応した。
- 一行に複数のURI
- 連続する各行にURI
- `http://www.example.com text` みたいなの

**Comment by okkez** [comment]
これで大抵のケースは大丈夫。

**Comment by okkez** [comment]
自分たちが使う範囲はdaimon側にテストを追加する。

**Comment by mtsmfm** [comment]
必要になったら open
