### ISSUE TITLE
Pagenate editor/posts#index

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#252]

**Comment by myokoym** [comment]
単純にページングしてしまうと以下の問題がありそうなので、中断して作戦を考えます。
- 特定の記事を編集したいときに探すのが大変になる
  - 今ならタイトルでページ内検索すればすぐ見つかる
- https://github.com/bm-sms/daimon-news-multi-tenant/tree/master/app/views/kaminari でカスタマイズしているので、スタイルを当てないと縦並びになってしまう

**Comment by myokoym** [comment]
ページングとは直接関係ないですが、「New Post」ボタンは一番上にあったほうがいいかもという話をしました。
（記事を書きたいだけなのに一番下までスクロールするのが手間のため）

**Comment by myokoym** [comment]
過去の記事を編集したい場面があまりないので、

> 特定の記事を編集したいときに探すのが大変になる 

は気にしなくてよさそう。（いざとなったらID直打ちで行ける）
必要になったら記事検索を編集画面に導入する手もある。

**Comment by myokoym** [comment]
> https://github.com/bm-sms/daimon-news-multi-tenant/tree/master/app/views/kaminari でカスタマイズしているので、スタイルを当てないと縦並びになってしまう

Kaminariのテンプレートを差し替えればよい。
