### ISSUE TITLE
著者情報を分解する

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#276]

**Comment by mtsmfm** [comment]
![image](https://cloud.githubusercontent.com/assets/1796864/13308016/033aa57e-dbb3-11e5-941b-3dbd27f60459.png)

**Comment by mtsmfm** [comment]
## TODO
- [ ] テーブル作る
- [ ] actor の登録画面
- [ ] 記事から credit を登録できるように
  - https://select2.github.io が便利そう?

CreditRole の登録画面はなくてもいい

**Comment by tricknotes** [comment]
actor -> participant で！
