### ISSUE TITLE
dyno が複数あるときに groonga 周りがまずそう

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#291]
- dyno A で記事を作って dyno B で消すとエラーになる
- dyno A で記事を更新して dyno B で見ると古い情報を元に関連検索をする

公開日の変更は、published scope が噛ませてあるので関連記事の表示数が減るだけで済みそう。

**Comment by kou** [comment]
> dyno A で記事を作って dyno B で消すとエラーになる

これは↓で直ったりしませんか？

``` diff
diff --git a/app/groonga/post_indexer.rb b/app/groonga/post_indexer.rb
index 03dc75f..9a81e80 100644
--- a/app/groonga/post_indexer.rb
+++ b/app/groonga/post_indexer.rb
@@ -28,7 +28,7 @@ class PostIndexer

   def remove(post)
     return if @posts.nil?
-    @posts[post.id].delete
+    @posts[post.id]&.delete
   end

   private
```

**Comment by okkez** [comment]
> dyno A で記事を更新して dyno B で見ると古い情報を元に関連検索をする

記事公開までに同期されるはずなので、未公開の記事ならば問題ないはず。
公開済みの記事ならば、dynoが1日1回再起動するからそれまで同期されないという問題。
検索結果にインパクトがあるくらいの記事の変更とは？
関連記事の場合だと、類似文書検索という機能を使っているので、少々の修正では検索結果は変わらなさそう。
ふつうの記事検索だと、ちょっと検索結果が変わるくらいになりそう。

**Comment by mtsmfm** [comment]
関連検索も、記事の内容の検索も、影響を受けるのは公開後に大きな変更を行った場合なので、そんなことほとんどありえないから 1 日 1 回の更新でいいかなぁーと思っています。

つまり、「dyno A で記事を更新して dyno B で見ると古い情報を元に関連検索をする」はたいした問題じゃないと思ってます。

で、その上で思ったのは、どうせ同期とれないので after_save や after_destroy の処理全部消しちゃえばいいかなと思いました。

また、groonga で引いてきたデータが古い可能性がある (ex. 公開後反響を受けて慌てて公開停止にした場合) ことを常に考慮して公開していいかどうかの scope はちゃんと噛ませてあげないといけないことは忘れないようにしないとですね。

**Comment by okkez** [comment]
`after_save`, `after_destroy` 消してリアルタイム同期を諦めるのはよさそうですね。
