### ISSUE TITLE
画像のアップロードに失敗することがある?

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#293]
`Rack app error: #<EOFError: bad content body>`

**Comment by okkez** [comment]
IE10の問題だったのでブラウザを変えてもらうことにした。

IE使ってる人には /admin や /editor 以下で警告を出すようにする？

**Comment by mtsmfm** [comment]
IE 10 で再現できたんでしたっけ

**Comment by okkez** [comment]
UAがIE10って書いてあったんでIE10だと思ってましたが、こちらでは未検証です。

**Comment by myokoym** [comment]
modern.IE のVMが手元にあるので検証してみます。

**Comment by myokoym** [comment]
ローカルへのアップロードは成功した。何か条件がある？

**Comment by myokoym** [comment]
S3へのアップロードも何度か試しましたが、エラーは出ませんでした。

**Comment by okkez** [comment]
再現しないなぁ。

http://qiita.com/marsa746079/items/a3c69465d605a0078a6b

こういう記事があって、一部の条件が一致しているのでこういう可能性はありそう。

**Comment by mtsmfm** [comment]
chrome 49 でも起きるっぽいことがわかった

**Comment by okkez** [comment]
Firefox でも起こるらしい

"HTTP_USER_AGENT"=>"Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0"

**Comment by okkez** [comment]
”Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"

**Comment by mtsmfm** [comment]
:tricknotes: < サムネイルの画像を本文のところに D&D してくると起きます!

**Comment by tricknotes** [comment]
エラーが発生すると 500 が返ってきますがユーザにはなにも起こらなかったようにみえる。

**Comment by tricknotes** [comment]
エディタの方で考慮が漏れているだけのように見えるので、ちゃんと状況を整理して適切なところに報告したいですね！

**Comment by mtsmfm** [comment]
とりあえずの対応を入れたので close (#335)
