### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by myokoym** [bm-sms/daimon-news-multi-tenant#297]
しばらくGitHubのREADMEを更新していなかったので、実態にそぐわないものになっている。
このままだと初めてさわる人が戸惑ってしまうので、早めにまとめ直したい。

[わかりやすいREADME.mdを書く | SOTA](http://deeeet.com/writing/2014/07/31/readme/)あたりを参考にするとよい？

**Comment by tricknotes** [comment]
あつくなってきた :fire:

**Comment by okkez** [comment]
daimon-news の立ち上げ方と手元での動かし方を書く。
管理画面へのアクセス方法も書く

**Comment by okkez** [comment]
コマンド羅列とherokuボタンがあればOK

**Comment by mtsmfm** [comment]
Move to https://github.com/bm-sms/daimon-news-misc/issues/89
