### ISSUE TITLE
カテゴリを階層化したい

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#308]
7 つ以上のものを認知するのは大変だからだ

**Comment by okkez** [comment]
parent_id 足して Category 自体を階層化できるようにすればよいのかしら。

**Comment by tricknotes** [comment]
カテゴリが20個ぐらい用意したくなりそうなので、それらが見やすい状態だと嬉しい(手段は階層化でなくてもよいのでは？)

**Comment by tricknotes** [comment]
サイドバー表示されるカテゴリと記事に設定するカテゴリが別々の管理できているだけで十分なので、グルーピングのような方法で実現できた方が簡単そう。

**Comment by tricknotes** [comment]
最初の段階(4/1)では、多すぎるカテゴリは非表示(クリックすると表示される)くらいで乗り切りたい

**Comment by okkez** [comment]
2階層まででOK

**Comment by tricknotes** [comment]
二段階作戦でいきたい
1. 管理画面でデータを登録できるようにする
2. デザインをあてた状態で公開する

**Comment by mtsmfm** [comment]
## 気にしないといけないこと
- パンくず
- デザイン
- データ移行

**Comment by ryota-sasabe** [comment]
https://github.com/bm-sms/nursepress/issues/169
まだふんわりしてますが、上記のような要望があるので着手する前に事業側にヒアリングしたほうがいいかもしれません。（daimonの文脈で取り入れるかは別にして）

**Comment by mtsmfm** [comment]
Move to https://github.com/bm-sms/daimon-news-misc/issues/86
