### ISSUE TITLE
view の中で `Model.find` したくない

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#327]
現状だと、`app/groonga/query.rb` がユーザの検索クエリをラップするクラスになっているで、その検索クエリを表示する際に苦しい感じになっている。

[例](https://github.com/bm-sms/daimon-news-multi-tenant/blob/9dd23dc781695a70f79eb953edeb2b18f443c755/app/views/search/search.html.haml#L8)

``` ruby
Participant.find(@query.participant_id).name
```

<del>
これを改善するために、ユーザからの入出力を担当するクラスを用意するとよいのではと思いました。
例えば form オブジェクトなんかを導入するといいんですかねぇ…。
</del>

`Query` の使い方をもっと工夫できる！はず！

**Comment by kou** [comment]
`app/groonga/query.rb`がformオブジェクトです！

**Comment by tricknotes** [comment]
なるほど！
ということは、現在は `Query` の使われ方が意図していない感じでしたか？

**Comment by kou** [comment]
よく見ていないんでわかんないですけど、`@query.participant.name`とか`@query.participant_name`とかできてもいい気がします！

**Comment by tricknotes** [comment]
なるほど！
それをやりたかったです！とってもしっくりきました！

**Comment by tricknotes** [comment]
(issue の description を更新しておきました)

**Comment by myokoym** [comment]
#325 の対応後にやる予定デス https://github.com/bm-sms/daimon-news-multi-tenant/pull/325#discussion_r55784100

**Comment by myokoym** [comment]
問題になっていたのは絞り込み（ドリルダウン）まわりのコードで、
現在は絞り込み機能は削除されているので`Model.find`されている箇所はないようす。

**Comment by tricknotes** [comment]
:sunglasses:
