### ISSUE TITLE
検索結果をスコア順にしたい

### ISSUE THREAD

**Issue by okkez** [bm-sms/daimon-news-multi-tenant#332]
Postに accessor を追加してスコアか search result を持たせて `sort_by` すればできそう。
ソートの回数は、PostgreSQL, Groonga のそれぞれから取り出す段階でidかpublished_atに揃えておけば、最小限にできるはず。

一方、関連記事の方はそもそも取得する記事数が5件と少ないので十分関連度の高い記事が抽出できているので現状のまま(published_at順)でよいと思う。

**Comment by mtsmfm** [comment]
いったんなし
