### ISSUE TITLE
検索の重み付け改善

### ISSUE THREAD

**Issue by okkez** [bm-sms/daimon-news-multi-tenant#339]
著者情報検索のレビュー対応（著者情報フルネームの順位を改善）
https://github.com/bm-sms/daimon-news-multi-tenant/commit/c15ca8bc8211a61f25b223838cb623390e6ebba2#commitcomment-16527154
 著者情報検索のレビュー対応（著者情報の重み付け改善）
https://github.com/bm-sms/daimon-news-multi-tenant/commit/c15ca8bc8211a61f25b223838cb623390e6ebba2#commitcomment-16557270

**Comment by tricknotes** [comment]
https://github.com/bm-sms/daimon-news-multi-tenant/pull/365 が入らないと、効果がなさそう

**Comment by mtsmfm** [comment]
consider after implementing score sorting
