### ISSUE TITLE
サイト管理者がひつよう？

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#348]
現状だと、サイト管理者はシステム上では表現されていない。
そのためその役割を管理者が担うことになりますが、これだとサイト立ち上げに必要なやり取りが煩雑になるのでは思われます。

**Comment by okkez** [comment]
サイト情報の編集だけできればよい

**Comment by mtsmfm** [comment]
もうちょい先であらためて考えよう
