### ISSUE TITLE
リンクや固定ページについての簡単な説明があったほうが親切

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#358]
`/editor` 以下のページはコンテキストなしで操作する人が多いと想定されるので、「これが何でどこにどう表示されるか」が簡単にでも説明されていると混乱を招かずにすむなと思いました。

**Comment by mtsmfm** [comment]
「関係者情報」という表現はわかりづらい
もここで考えよう

**Comment by mtsmfm** [comment]
各概念について、一行程度の説明文を書いておく

**Comment by okkez** [comment]
- index の h1 の下に説明文
- 各フォームのフィールドに必要ならばヘルプテキスト

**Comment by okkez** [comment]
説明付けた方がよさそうなもの
- credit_roles の order
- categories の slug と order
- fixed_pages の slug
- links の order と url (絶対URLなのか相対URLなのかわからなくなりそう)
- participants の photo
- posts の credit_roles と category_id, serial_id, thumbnail(画像サイズについて), published_at
- serials の slug

これ以外は雰囲気でわかるはず。

**Comment by okkez** [comment]
adminのサイト情報のフォームの説明は英語で書く。

日本語でいいので以下の説明を教えてください。
- tagline
- content_header_url
- promotion_url
- menu_url
- home_url
- footer_url
- ad_client
- ad_slot
- head_tag
- promotion_tag

これ以外はわかるので、書けそう。

**Comment by okkez** [comment]
一通り書いた。
