### ISSUE TITLE
検索結果の <title> で検索クエリがサニタイズされて表示されている

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#385]
これはエスケープして表示されるのがよいのでは。

**Comment by tricknotes** [comment]
タグっぽい部分が削除されて表示されていました。
例: `<test>hoi` -> `hoi`

**Comment by tricknotes** [comment]
`TextNormalizer.normalize_title` でサニタイズされているっぽいので、オプションでどうにかするのは難しそう… https://github.com/kpumuk/meta-tags/blob/v2.1.0/lib/meta_tags/meta_tags_collection.rb#L90

**Comment by mtsmfm** [comment]
ふむ〜

**Comment by mtsmfm** [comment]
まぁ記号入れないと影響ないからとりあえずは...

**Comment by mtsmfm** [comment]
Move to https://github.com/bm-sms/daimon-news-misc/issues/87
