### ISSUE TITLE
関係者情報で検索したときの検索結果を改善する

### ISSUE THREAD

**Issue by myokoym** [bm-sms/daimon-news-multi-tenant#392]
ref: #371, #376

https://github.com/bm-sms/daimon-news-multi-tenant/issues/371#issuecomment-197719924 で指摘があった問題。

> （`record.participants.name =~ ...`とかバグってるな。。。複数キーワードを指定したときに全部で検索してしまっている。。。）

スペース区切りで複数キーワードを指定した場合、記事と関係者名と関係者説明をそれぞれ別々にAND検索してしまっているため、それぞれに複数キーワードがすべて含まれていないとヒットしなくなっていました。

例としては、「title author」で検索したとき、関係者名単体で「title」と「author」が含まれていないとヒットしない状況でした。（本来は、記事に「title」が含まれていれば、関係者名に「title」が含まれなくてもヒットするのが期待される）

加えて、 https://github.com/bm-sms/daimon-news-multi-tenant/pull/376#discussion_r56936189 の指摘にも対応する:

> うーん、 `participants` でマッチしてもそのことがユーザにはわからないんですね…。
> participants のマッチした部分を表示するか、一旦ここは機能を封印するかした方が整合性がある状態に感じるんですがいかがでしょう…？

**Comment by myokoym** [comment]
> participants のマッチした部分を表示するか、一旦ここは機能を封印するかした方が整合性がある状態に感じるんですがいかがでしょう…？

スニペットに表示されないよりも検索対象外になるほうが不便かなあと思うので、封印するのはやめたいです。
遅くなりましたが案を考えました。
- 案1: スニペット（現在は記事本文のみ）に関係者情報を追加する
  - メリット: DOMやデザインの変更が不要
  - デメリット: 記事本文にマッチしたのか関係者情報などのメタ情報にマッチしたのかわかりづらい
- 案2: マッチした関係者情報を別の場所（記事とは別のスニペット、もしくはタグのようなもの）で表示する
  - メリット: 記事本文にマッチしたのか関係者情報などのメタ情報にマッチしたのかわかりやすい
  - デメリット: DOMやデザインの変更が必要
- 案3: 関係者情報は検索結果画面には表示しない
  - メリット: 変更不要
  - デメリット: 関係者情報でマッチしてもそのことがユーザにはわからない

**Comment by okkez** [comment]
他のところと比べると優先度は低いので今は何もしないことにした。
