### ISSUE TITLE
記事の public_id を入力可能にする

### ISSUE THREAD

**Issue by ryota-sasabe** [bm-sms/daimon-news-multi-tenant#403]
記事の一括移行後に新規登録された記事については、現状の public_id が連番で付与される仕様だと番号が合わなくなる懸念があるため。

**Comment by ryota-sasabe** [comment]
本対応は、移行期間のみの暫定仕様になる。
4/6 に移行が終わったら、元に戻す想定。

仕様検討
- public_id は、データとしては必須だが、記事編集画面からの入力を必須にするかどうか。
  - 入力必須にする
  - 入力任意にして、入力がなかったら、最大値 + 1 を自動的に設定する
    - →編集担当に確認
- 他媒体はどうするか
  - →public_id の入力項目を表示しない（意識させない）
- すでに存在する public_id の場合は、重複エラーとする

**Comment by tricknotes** [comment]
> 他媒体はどうするか

媒体ごとに処理を切り替えるもの大変なので、ひとまず全部表示しておいて運用でカバー(!)するのがお安そうに感じました。

**Comment by okkez** [comment]
必須にしてしまうと、他の媒体で辛いので任意にしたいですね。

**Comment by okkez** [comment]
> すでに存在する public_id の場合は、重複エラーとする

public_idはサイトごとに独立しているので、注意が必要です。

**Comment by ryota-sasabe** [comment]
public_id と site_id の掛け合わせで重複チェックですね！
媒体ごとの処理はなくそうか。。

**Comment by okkez** [comment]
フィーチャーフラグは避けてきたので、媒体ごとの処理はやらない方向にしたいです。

**Comment by tricknotes** [comment]
> public_id と site_id の掛け合わせで重複チェックですね！

ですね！
いまいまだとユニークインデックスが貼らさっているので、データの整合性という面では気にしなくてよさそうです。 https://github.com/bm-sms/daimon-news-multi-tenant/blob/master/db/schema.rb#L125

とはいえ、重複して保存しようとするとエラー画面が表示されてしまうので、validation を追加すれば完了しそうです！

**Comment by tricknotes** [comment]
Closed by https://github.com/bm-sms/daimon-news-multi-tenant/pull/411
Thanks @ryota-sasabe :whale:
