### ISSUE TITLE
検索結果のスニペットが複数存在する時に、それらの区切りがわかりづらい

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#404]
スニペット前後に `…` を入れたりするとわかりやすいのかな…。

というのを[こちらの検索結果](http://www.clear-code.com/ranguba/search/?query=%E3%83%86%E3%82%B9%E3%83%88)を見ていて思いつきました。

**Comment by kou** [comment]
`snippets.join("<br>")`みたいにしているところがある（私がこんな感じで動きますよと出したコードではそうしていました。スタイルをあてるのはサボりたかったので。）と思うんですが、それを`join("...")`にするとそうなりますよ！

ちなみに、るりまサーチではそうしています。
https://github.com/clear-code/rurema-search/blob/master/lib/rurema_search/groonga_searcher.rb#L1205-L1208

**Comment by tricknotes** [comment]
なるほどー！
有益な情報ありがとうございます！

このあたりは実際にデザインがあたった状態でみて気づいたことなので、これからそんな感じの見た目にしてもよさそうですね！
