### ISSUE TITLE
サブドメのときのリンクがサブディレクトリになってる

### ISSUE THREAD

**Issue by mtsmfm** [bm-sms/daimon-news-multi-tenant#6]
http://site1.daimon-news-multi-tenant.54.225.166.43.xip.io/blog

のリンクが

http://site1.daimon-news-multi-tenant.54.225.166.43.xip.io/blog/sites/1/posts/277846598

になってる

**Comment by myokoym** [comment]
目的: Rails単体でリバースプロキシと同等のことができるかどうか検証すること。

**Comment by myokoym** [comment]
現時点では以下の挙動になっている。
:site_idがURLに含まれなくなったので、それほど気にならなくなった。
- `http://site1.example.com/` で記事一覧が表示される（`http://site1.example.com/posts`と同じ内容）
- 個別の記事のリンクをクリックすると `http://site1.example.com/posts/1` に遷移する

**Comment by myokoym** [comment]
今は http://site1.example.com/posts/1 と http://site1.example.com/sites/1/posts/1 同じ内容。

**Comment by myokoym** [comment]
http://site1.example.com/sites/1/posts/1 で戻るリンクをクリックすると http://site1.example.com/posts に遷移する（URLのパスが変わってしまう）が、 http://site1.example.com/sites/1/posts/1 はデバッグ用なのでひとまずいいことにする。

**Comment by myokoym** [comment]
現在の挙動で大丈夫そうなので閉じます。問題になりそうならreopenお願いします。
