### ISSUE TITLE
Return 404 when page is not found

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#627]
See for detail: https://github.com/bm-sms/nursepress/issues/335

**Comment by fukumame** [comment]
@tricknotes 
Can I challenge this issue?
昨日の宣言通り、こちらのissue対応、僕の方で実施してみても良いですか？

**Comment by tricknotes** [comment]
@fukumame 
Yes, of course! You are awesome!
もちろんです、わたしはしばらく手を付けられなさそうなので、もし見てもらえると泣いて喜びます！
