### ISSUE TITLE
no schema.rb?

### ISSUE THREAD

**Issue by naofumi-fujii** [bm-sms/daimon-news-multi-tenant#666]
it still works, but any reason?

**Comment by mtsmfm** [comment]
We use SQL as schema format

https://github.com/bm-sms/daimon-news/blob/master/config/application.rb#L26
https://github.com/bm-sms/daimon-news/blob/master/db/structure.sql

Our application has some SQL which works only postgresql for migration.

**Comment by naofumi-fujii** [comment]
great!
thanks for reply 👍
