### ISSUE TITLE
Difference between Post.updated_at, Post.original_updated_at?

### ISSUE THREAD

**Issue by naofumi-fujii** [bm-sms/daimon-news-multi-tenant#667]
i can guess about updated_at( seems like activerecord default.
what is Post.original_updated_at for?

**Comment by mtsmfm** [comment]
It's not necessary anymore...
We can remove that column :put_litter_in_its_place: 
We need this column to sync some posts from another application at a time in the past.

**Comment by naofumi-fujii** [comment]
thanks for the information! 😉
