### ISSUE TITLE
サイトオーナーを導入したい

### ISSUE THREAD

**Issue by okkez** [bm-sms/daimon-news-multi-tenant#67]

**Comment by okkez** [comment]
書いていたコメントを消してしまった。。。 :cry:

UserとSiteをN:M関連にすれば、Roleモデルは作らなくてもできそう。
N:M関連にするとActiveAdminで扱えるのかどうかが疑問。
(ActiveAdminは最終的には捨ててもいいかと思っている)

**Comment by tricknotes** [comment]
一旦、ユーザーは管理者としてそれ以外の機能を全部消す。
その後、サイトオーナーを導入したい。

**Comment by mtsmfm** [comment]
dup #198
