### ISSUE TITLE
記事ページの `<link rel="next">` に次・前ページのリンクを設定する

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#85]
関連: https://github.com/bm-sms/daimon-news-multi-tenant/issues/83

**Comment by mtsmfm** [comment]
https://github.com/bm-sms/daimon-news-multi-tenant/blob/master/app/views/kaminari/post/_page.html.haml#L2

やってあった

**Comment by mtsmfm** [comment]
a タグは終わってたけど link タグは終わってなかったです :bow:
