### ISSUE TITLE
メタタグを設定できるようにする

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-news-multi-tenant#9]

**Comment by tricknotes** [comment]
favicon も設定できるようにする

**Comment by myokoym** [comment]
Active Admin では config.meta_tags で設定できる。
https://github.com/bm-sms/daimon-news-multi-tenant/blob/master/config/initializers/active_admin.rb#L164
https://github.com/activeadmin/activeadmin/blob/v1.0.0.pre2/lib/active_admin/views/pages/base.rb#L38

**Comment by myokoym** [comment]
ひとまずMetaTagsテーブルを作ってみよう…

```
% bin/rails g scaffold meta_tags name content site:references
```

（OGPはnameじゃなくてpropertyみたいだけど、それはあとからかんがえる）

**Comment by myokoym** [comment]
favicon は #53 で。

**Comment by myokoym** [comment]
画面ごとにメタタグを変える場合の実装案memo
- pathカラムを追加
  - メタタグが可変なのがFixedPagesのみであれば、fixed_page_idカラムでもいいかも
- 1行1タグではなく、1行1ページにする
  - カラムを汎用的（name, content）にするのをやめる
  - カラムのkeyをname（descriptionやrobots）にして、valueをcontentにする

**Comment by myokoym** [comment]
> 画面ごとにメタタグを変える場合の実装案memo

https://github.com/bm-sms/daimon-news-multi-tenant/tree/meta-tags-2 で対応中です。
明日rebaseなどしてpull request出します。

**Comment by myokoym** [comment]
テーブル名はmeta_tagsじゃないほうがいい気がしてきた。
（1レコードで複数のメタタグを扱うのと、ページごとのタイトルも設定したいので）

meta_informationsとかpage_meta_dataとか…？

**Comment by myokoym** [comment]
メタ情報用のテーブルを作るとどうしても複雑になってしまうので、
そもそもテーブルを作らずに既存の情報を使ったほうがよさそうという話をしました。
noindexが少し気になりますが、slug決め打ちでいいのでは？という流れです。

**Comment by myokoym** [comment]
memo:
- スキーマをいじるにしても、fixed_pagesテーブルにカラムを追加するくらいで済みそう
- categoriesテーブルはdescriptionを持っているし

**Comment by myokoym** [comment]
#92 で進行中です
